services:
  vLLM-Qwen:
    image: vllm/vllm-openai:latest
    container_name: vllm-qwen



    environment:
      HF_HUB_CACHE: /mnt/data/vLLM/models
      VLLM_LOGGING_LEVEL: DEBUG


    ports:
      - "127.0.0.1:15050:8000"
    command: >
      --model QuantTrio/Qwen3.5-27B-AWQ
      --served-model-name Qwen3.5-27B-AWQ
      --quantization awq_marlin
      --trust-remote-code
      --language-model-only
      --host 0.0.0.0
      --port 8000
      --max-model-len 8192
      --gpu-memory-utilization 0.88
      --max-num-seqs 12
      --default-chat-template-kwargs '{"enable_thinking": false}'
      --api-key ${VLLM_API_KEY}
    restart: unless-stopped
    ipc: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
