services:
  vllm-gpt-oss-20b:
    image: vllm/vllm-openai:latest
    container_name: vllm-gpt-oss-20b

    expose:
      - "8000"
      
    volumes:
      - /mnt/sdb/models:/app/models
    
    command: >
      --model /app/models/gpt-oss-20b
      --served-model-name gpt-oss-20b
      --host 0.0.0.0
      --port 8000
      --model /app/models/gpt-oss-20b
      --served-model-name gpt-oss-20b
      --max_model_len 8192
      --cpu-offload-gb 40
#      --gpu-memory-utilization 0.75

    restart: unless-stopped
    ipc: host

    networks:
      - ai-patients-network

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
networks:
  ai-patients-network:
    external: true
